spring:
  application:
    name: testcontainers
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: false
  session:
    store-type: redis
    timeout: 30m
    redis:
      namespace: ${SESSION_NAMESPACE:testcontainers:session}
  data:
    redis:
      timeout: 2s
  security:
    oauth2:
      client:
        registration:
          github:
            provider: github
            client-id: ${OAUTH_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH_GITHUB_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: read:user
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
app:
  security:
    frontend-url: http://127.0.0.1:5173
    allowed-origins: http://127.0.0.1:5173
